In [1]:
import pandas as pd
from functools import reduce
from concurrent.futures import ThreadPoolExecutor
import requests
from urllib.parse import urlencode
import json
import requests
import pandas
import os
from pandas.io.json import json_normalize
import numpy as np

In [2]:
os.environ['Nfer_Access_Key'] = "praveen@nference.net"
os.environ['Nfer_Secret_Key'] = "81d4782ff7cda46fdbd1c2b758af0759"

PRESTAGING_COOKIE = {
"Cookie":"csrftoken=wLgolDsSbcb3Py2xB8xuiRDmwezQ9Y9o; sessionid=jqab5fdwqmrxrnc5u0cli8xqxerep2p2"}

headers = {}
headers["cookie"] = "csrftoken=wLgolDsSbcb3Py2xB8xuiRDmwezQ9Y9o; sessionid=jqab5fdwqmrxrnc5u0cli8xqxerep2p2"

In [295]:
def get_enrichment(hgnc_id,ensemble_id,lowrange,highrange,entity):
    url = "https://preview.nferx.com/dv/201912/rnaapi2/entity_distribution?"
    
    params = {
        "entity_type":entity,
        "range_a_min":lowrange[0],
        "range_a_max":lowrange[1],
        "range_b_min":highrange[0],
        "range_b_max":highrange[1],
        "enriched_group": "B",
        "exclude_zero": True,
        "token_extraction": "ngram",
        "single_cell_filter":"not_single_cell",
        "cell_line_filter":"not_cell_line",
        "exclude_zero":True,
        "gene_id":ensemble_id,
        "hgnc_id":hgnc_id
    }

    x = requests.get(url, params=params, headers = headers)
    required_table = json_normalize(x.json()['result']['term_features'])
    return(required_table)

In [4]:
all_IL1A_disease_enriched = get_enrichment("il1a","ensg00000115008",[0,0.07],[0.0,14],"root-diseases")

In [5]:
all_IL1A_disease_enriched

,neg_log_p_bh_adjusted_p,term,sub_entity_type,range_a_count,range_b_count,all_studies_count,gtex_studies_count,tcga_studies_count,signal_token,annotation,ls,gs
0,0.000000,mitral_valve_regurgitation,,0,1,1,0,0,mitral_valve_regurgitation,[],0.00,0.0
1,0.000000,neurogenic_bladder,,0,1,1,0,0,neurogenic_bladder,[],0.00,0.0
2,0.000000,sccb,,0,7,1,0,0,sccb,[],0.00,0.0
3,2.789372,h5n1,,0,42,4,0,0,h5n1,[],0.00,0.0
4,0.000000,serous_carcinoma,,0,4,2,0,0,serous_carcinoma,[],0.04,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
356,0.000000,monosomy_21,,0,2,1,0,0,monosomy_21,[],0.00,0.0
357,0.000000,ppcd,,0,1,1,0,0,ppcd,[],0.00,0.0
358,0.000000,anaplastic_oligodendroglioma,disease,0,1,1,0,0,anaplastic_oligodendroglioma,[],0.00,0.0
359,0.000000,ataxia_telangiectasia,disease,0,6,1,0,0,ataxia_telangiectasia,[],0.68,0.0
360,49.419930,breast_cancer,disease,169,1974,36,0,0,breast_cancer,[],4.17,0.0

In [6]:
all_IL1A_disease_enriched.to_csv('/Users/praveenanand/Documents/Apps/Bermekimab_LabelExpansen_Janssen_May2020/Deliverable2_again/Data/IL1A_RNAseq_disease_enrichment_allrange.csv', index=False)

In [300]:
all_IL1A_disease_enriched_updated = get_enrichment("il1a","ensg00000115008",[0,0.06],[3.68,14],"root-diseases")
all_IL1A_disease_enriched_updated.to_csv('/Users/praveenanand/Documents/Apps/Bermekimab_LabelExpansen_Janssen_May2020/Deliverable2_again/Data/IL1A_RNAseq_disease_enrichment_allrange_updated.csv', index=False)

In [299]:
all_IL1A_disease_enriched_updated = get_enrichment("il1a","ensg00000115008",[0,0.06],[3.68,14],"root-diseases")
all_IL1A_disease_enriched_updated.loc[all_IL1A_disease_enriched_updated['term'] == 'lupus']

,neg_log_p_bh_adjusted_p,term,sub_entity_type,range_a_count,range_b_count,all_studies_count,gtex_studies_count,tcga_studies_count,signal_token,annotation,ls,gs
45,32.802905,lupus,,28,80,1,0,0,lupus,[],3.35,0.0

In [8]:
all_IL1A_disease_enriched_updated = get_enrichment("il1a","ensg00000115008",[0,3.859],[3.86,14],"root-diseases")
all_IL1A_disease_enriched.to_csv('/Users/praveenanand/Documents/Apps/Bermekimab_LabelExpansen_Janssen_May2020/Deliverable2_again/Data/IL1A_RNAseq_disease_enrichment_allrange_updated_allrange.csv', index=False)

In [11]:
all_IL1A_disease_enriched_updated

In [21]:
def get_enrichment(hgnc_id,ensemble_id,lowrange,highrange,entity):
    url = "https://preview.nferx.com/dv/201912/rnaapi2/entity_distribution?"
    params = {
        "entity_type":entity,
        "range_a_min":lowrange[0],
        "range_a_max":lowrange[1],
        "range_b_min":highrange[0],
        "range_b_max":highrange[1],
        "enriched_group": "B",
        "exclude_zero": True,
        "token_extraction": "ngram",
        "single_cell_filter":"not_single_cell",
        "cell_line_filter":"not_cell_line",
        "exclude_zero":True,
        "gene_id":ensemble_id,
        "hgnc_id":hgnc_id
    }
    x = requests.get(url, params=params, headers = headers)
    required_table = json_normalize(x.json()['result']['term_features'])
    return(required_table)
all_IL1A_disease_enriched_actual = get_enrichment("il1a","ensg00000115008",[0,0.06],[3.68,14],"root-diseases")

In [55]:
all_IL1A_disease_enriched_all = get_enrichment("il1a","ensg00000115008",[0,0.06],[0,14],"root-diseases")
all_IL1A_disease_enriched_all.loc[all_IL1A_disease_enriched_all['term'] == 'squamous_cell_carcinoma']

,neg_log_p_bh_adjusted_p,term,sub_entity_type,range_a_count,range_b_count,all_studies_count,gtex_studies_count,tcga_studies_count,signal_token,annotation,ls,gs
92,39.54073,squamous_cell_carcinoma,disease,15,712,19,0,4,squamous_cell_carcinoma,[tcga_evidence],2.66,0.0

In [25]:
all_IL1A_disease_enriched_actual = get_enrichment("il1a","ensg00000115008",[0,0.06],[3.68,14],"root-diseases")
all_IL1A_disease_enriched_actual.loc[all_IL1A_disease_enriched_actual['term'] == 'squamous_cell_carcinoma']

,neg_log_p_bh_adjusted_p,term,sub_entity_type,range_a_count,range_b_count,all_studies_count,gtex_studies_count,tcga_studies_count,signal_token,annotation,ls,gs
25,73.882236,squamous_cell_carcinoma,disease,15,132,8,0,1,squamous_cell_carcinoma,[tcga_evidence],2.66,0.0

In [53]:
all_IL1A_disease_enriched_med = get_enrichment("il1a","ensg00000115008",[0,0.06],[0.061,3.6799],"root-diseases")
all_IL1A_disease_enriched_med.loc[all_IL1A_disease_enriched_med['term'] == 'squamous_cell_carcinoma']

,neg_log_p_bh_adjusted_p,term,sub_entity_type,range_a_count,range_b_count,all_studies_count,gtex_studies_count,tcga_studies_count,signal_token,annotation,ls,gs
29,42.822632,squamous_cell_carcinoma,disease,15,565,19,0,4,squamous_cell_carcinoma,[tcga_evidence],2.66,0.0

In [54]:
all_IL1A_disease_enriched_low = get_enrichment("il1a","ensg00000115008",[0,0.06],[0,0.06],"root-diseases")
all_IL1A_disease_enriched_low.loc[all_IL1A_disease_enriched_low['term'] == 'squamous_cell_carcinoma']

,neg_log_p_bh_adjusted_p,term,sub_entity_type,range_a_count,range_b_count,all_studies_count,gtex_studies_count,tcga_studies_count,signal_token,annotation,ls,gs
378,0,squamous_cell_carcinoma,disease,15,15,7,0,2,squamous_cell_carcinoma,[tcga_evidence],2.66,0.0

In [63]:
test = all_IL1A_disease_enriched_low.loc[all_IL1A_disease_enriched_low['term'] == 'squamous_cell_carcinoma']
test['term'].values[0]

'squamous_cell_carcinoma'

In [86]:
all_IL1A_disease_enriched_all = get_enrichment("il1a","ensg00000115008",[0,0.06],[0.061,14],"root-diseases")
all_IL1A_disease_enriched_all.loc[all_IL1A_disease_enriched_all['term'] == 'lupus']

Empty DataFrame
Columns: [neg_log_p_bh_adjusted_p, term, sub_entity_type, range_a_count, range_b_count, all_studies_count, gtex_studies_count, tcga_studies_count, signal_token, annotation, ls, gs]
Index: []

In [117]:
def get_disease_numbers(diseasename):
    all_IL1A_disease_enriched_all = get_enrichment("il1a","ensg00000115008",[0,0.06],[0,14],"root-diseases")
    required_dataall = all_IL1A_disease_enriched_all.loc[all_IL1A_disease_enriched_all['term'] == diseasename]
    
    all_IL1A_disease_enriched_actual = get_enrichment("il1a","ensg00000115008",[0,0.06],[3.68,14],"root-diseases")
    required_datahigh = all_IL1A_disease_enriched_actual.loc[all_IL1A_disease_enriched_actual['term'] == diseasename]
    
    all_IL1A_disease_enriched_med = get_enrichment("il1a","ensg00000115008",[0,0.06],[0.061,3.6799],"root-diseases")
    required_datamed = all_IL1A_disease_enriched_med.loc[all_IL1A_disease_enriched_med['term'] == diseasename]
    
    all_IL1A_disease_enriched_low = get_enrichment("il1a","ensg00000115008",[0,0.00001],[0,0.06],"root-diseases")
    required_datalow = all_IL1A_disease_enriched_low.loc[all_IL1A_disease_enriched_low['term'] == diseasename]
    
    #combined_result = str(required_datahigh['neg_log_p_bh_adjusted_p'].values[0]) + "," + str(required_datahigh['range_b_count'].values[0]) + "," + str(required_datahigh['all_studies_count'].values[0]) + "," + str(required_datahigh['range_a_count'].values[0]) + "," + str(required_datalow['all_studies_count'].values[0]) + "," + str(required_datamed['range_b_count'].values[0]) + "," + str(required_datamed['all_studies_count'].values[0]) + "," + str(required_dataall['range_b_count'].values[0]) + "," + str(required_dataall['all_studies_count'].values[0])
    
    return(required_datahigh)

In [80]:
get_disease_numbers('squamous_cell_carcinoma')

'73.88223559773495,132,8,15,7,565,19,712,19'

In [108]:
get_disease_numbers('lupus')

Empty DataFrame
Columns: [neg_log_p_bh_adjusted_p, term, sub_entity_type, range_a_count, range_b_count, all_studies_count, gtex_studies_count, tcga_studies_count, signal_token, annotation, ls, gs]
Index: []

In [101]:
get_disease_numbers('acute_on_chronic_liver_failure')

,neg_log_p_bh_adjusted_p,term,sub_entity_type,range_a_count,range_b_count,all_studies_count,gtex_studies_count,tcga_studies_count,signal_token,annotation,ls,gs
110,3.923852,acute_on_chronic_liver_failure,disease,0,61,2,0,0,acute_on_chronic_liver_failure,[],0.0,0.0

In [113]:
url = "https://preview.nferx.com/dv/201912/rnaapi2/entity_distribution?"

#https://preview.nferx.com/rnaapi2/entity_distribution?hgnc_id=il1a&gene_id=ensg00000115008&range_a_min=0&range_a_max=0.07&range_b_min=3.86&range_b_max=14&entity_type=root-cells-and-tissues&enriched_group=B&cell_line_filter=not_cell_line&single_cell_filter=not_single_cell&exclude_zero=true&token_extraction=ngram

params = {
    "entity_type":"root-diseases",
    "range_a_min":0,
    "range_a_max":0.06,
    "range_b_min":3.6799,
    "range_b_max":14,
    "enriched_group": "B",
    "exclude_zero": True,
    "token_extraction": "ngram",
    "single_cell_filter":"not_single_cell",
    "cell_line_filter":"all",
    "exclude_zero":True,
    "gene_id":"ensg00000115008",
    "hgnc_id":"IL1A"
}

x = requests.get(url, params=params, headers = headers)
all_data = json_normalize(x.json()['result']['term_features'])
all_data.loc[all_data['term'] == 'lupus']

,neg_log_p_bh_adjusted_p,term,sub_entity_type,range_a_count,range_b_count,all_studies_count,gtex_studies_count,tcga_studies_count,signal_token,annotation,ls,gs
59,35.544832,lupus,,28,80,1,0,0,lupus,[],3.37,0

In [115]:
url = "https://preview.nferx.com/dv/201912/rnaapi2/entity_distribution?"

#https://preview.nferx.com/rnaapi2/entity_distribution?hgnc_id=il1a&gene_id=ensg00000115008&range_a_min=0&range_a_max=0.07&range_b_min=3.86&range_b_max=14&entity_type=root-cells-and-tissues&enriched_group=B&cell_line_filter=not_cell_line&single_cell_filter=not_single_cell&exclude_zero=true&token_extraction=ngram

params = {
    "entity_type":"root-diseases",
    "range_a_min":0,
    "range_a_max":0.06,
    "range_b_min":0.061,
    "range_b_max":14,
    "enriched_group": "B",
    "exclude_zero": True,
    "token_extraction": "ngram",
    "single_cell_filter":"not_single_cell",
    "cell_line_filter":"all",
    "exclude_zero":True,
    "gene_id":"ensg00000115008",
    "hgnc_id":"IL1A"
}

x = requests.get(url, params=params, headers = headers)
all_data = json_normalize(x.json()['result']['term_features'])
all_data.loc[all_data['term'] == 'lupus']

Empty DataFrame
Columns: [neg_log_p_bh_adjusted_p, term, sub_entity_type, range_a_count, range_b_count, all_studies_count, gtex_studies_count, tcga_studies_count, signal_token, annotation, ls, gs]
Index: []

In [118]:
get_disease_numbers('breast_cancer')

,neg_log_p_bh_adjusted_p,term,sub_entity_type,range_a_count,range_b_count,all_studies_count,gtex_studies_count,tcga_studies_count,signal_token,annotation,ls,gs
45,45.28819,breast_cancer,disease,163,191,3,0,0,breast_cancer,[],4.17,0.0

In [ ]:
https://preview.nferx.com/rnaapi2/term_distribution?gene_id=ensg00000115008&range_a_min=0&range_a_max=0.06&range_b_min=.061&range_b_max=14&entity_type=root-diseases&enriched_group=B&cell_line_filter=not_cell_line&exclude_zero=true&token_extraction=ngram&term=lupus

In [124]:
url = "https://preview.nferx.com/dv/201912/rnaapi2/term_distribution?"

#https://preview.nferx.com/rnaapi2/entity_distribution?hgnc_id=il1a&gene_id=ensg00000115008&range_a_min=0&range_a_max=0.07&range_b_min=3.86&range_b_max=14&entity_type=root-cells-and-tissues&enriched_group=B&cell_line_filter=not_cell_line&single_cell_filter=not_single_cell&exclude_zero=true&token_extraction=ngram

params = {
    "entity_type":"root-diseases",
    "range_a_min":0,
    "range_a_max":0.0001,
    "range_b_min":0.001,
    "range_b_max":14,
    "enriched_group": "B",
    "exclude_zero": True,
    "token_extraction": "ngram",
    "single_cell_filter":"not_single_cell",
    "cell_line_filter":"all",
    "exclude_zero":True,
    "gene_id":"ensg00000115008",
    "hgnc_id":"IL1A",
    "term" : "lupus"
}

x = requests.get(url, params=params, headers = headers)
all_data = json_normalize(x.json()['result']['term_features']['studies_found'])
all_data

,study_id,total_sample_count,study_title,study_type,study_link,samples_a,samples_b,samples_a_cell_line,samples_b_cell_line,samples_a_single_cell,samples_b_single_cell
0,GSE110685,53,Low density granulocytes and their gene signat...,GEO,https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi...,0,11,0,0,0,0
1,GSE124939,164,Hypersensitive interferon responses in lupus k...,GEO,https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi...,0,81,0,0,0,0
2,GSE139358,41,"Transcriptomic, epigenetic and functional anal...",GEO,https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi...,0,20,0,0,0,0
3,GSE86884,96,Differentially Expressed Gene Transcripts Usin...,GEO,https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi...,0,2,0,0,0,0

In [122]:
url = "https://preview.nferx.com/dv/201912/rnaapi2/term_distribution?"

#https://preview.nferx.com/rnaapi2/entity_distribution?hgnc_id=il1a&gene_id=ensg00000115008&range_a_min=0&range_a_max=0.07&range_b_min=3.86&range_b_max=14&entity_type=root-cells-and-tissues&enriched_group=B&cell_line_filter=not_cell_line&single_cell_filter=not_single_cell&exclude_zero=true&token_extraction=ngram

params = {
    "entity_type":"root-diseases",
    "range_a_min":0,
    "range_a_max":0.06,
    "range_b_min":3.68,
    "range_b_max":14,
    "enriched_group": "B",
    "exclude_zero": True,
    "token_extraction": "ngram",
    "single_cell_filter":"not_single_cell",
    "cell_line_filter":"all",
    "exclude_zero":True,
    "gene_id":"ensg00000115008",
    "hgnc_id":"IL1A",
    "term" : "lupus"
}

x = requests.get(url, params=params, headers = headers)
all_data = json_normalize(x.json()['result']['term_features']['studies_found'])
all_data

,study_id,total_sample_count,study_title,study_type,study_link,samples_a,samples_b,samples_a_cell_line,samples_b_cell_line,samples_a_single_cell,samples_b_single_cell
0,GSE124939,164,Hypersensitive interferon responses in lupus k...,GEO,https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi...,0,80,0,0,0,0

In [125]:
url = "https://preview.nferx.com/dv/201912/rnaapi2/term_distribution?"

#https://preview.nferx.com/rnaapi2/entity_distribution?hgnc_id=il1a&gene_id=ensg00000115008&range_a_min=0&range_a_max=0.07&range_b_min=3.86&range_b_max=14&entity_type=root-cells-and-tissues&enriched_group=B&cell_line_filter=not_cell_line&single_cell_filter=not_single_cell&exclude_zero=true&token_extraction=ngram

params = {
    "entity_type":"root-diseases",
    "range_a_min":0,
    "range_a_max":0.06,
    "range_b_min":0.061,
    "range_b_max":3.68,
    "enriched_group": "B",
    "exclude_zero": True,
    "token_extraction": "ngram",
    "single_cell_filter":"not_single_cell",
    "cell_line_filter":"all",
    "exclude_zero":True,
    "gene_id":"ensg00000115008",
    "hgnc_id":"IL1A",
    "term" : "lupus"
}

x = requests.get(url, params=params, headers = headers)
all_data = json_normalize(x.json()['result']['term_features']['studies_found'])
all_data

,study_id,total_sample_count,study_title,study_type,study_link,samples_a,samples_b,samples_a_cell_line,samples_b_cell_line,samples_a_single_cell,samples_b_single_cell
0,GSE124939,164,Hypersensitive interferon responses in lupus k...,GEO,https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi...,0,1,0,0,0,0
1,GSE139358,41,"Transcriptomic, epigenetic and functional anal...",GEO,https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi...,15,5,0,0,0,0

In [127]:
url = "https://preview.nferx.com/dv/201912/rnaapi2/term_distribution?"

#https://preview.nferx.com/rnaapi2/entity_distribution?hgnc_id=il1a&gene_id=ensg00000115008&range_a_min=0&range_a_max=0.07&range_b_min=3.86&range_b_max=14&entity_type=root-cells-and-tissues&enriched_group=B&cell_line_filter=not_cell_line&single_cell_filter=not_single_cell&exclude_zero=true&token_extraction=ngram

params = {
    "entity_type":"root-diseases",
    "range_a_min":0,
    "range_a_max":0.0001,
    "range_b_min":0.0001,
    "range_b_max":0.06,
    "enriched_group": "B",
    "exclude_zero": True,
    "token_extraction": "ngram",
    "single_cell_filter":"not_single_cell",
    "cell_line_filter":"all",
    "exclude_zero":True,
    "gene_id":"ensg00000115008",
    "hgnc_id":"IL1A",
    "term" : "lupus"
}

x = requests.get(url, params=params, headers = headers)
all_data = json_normalize(x.json()['result']['term_features']['studies_found'])
all_data

,study_id,total_sample_count,study_title,study_type,study_link,samples_a,samples_b,samples_a_cell_line,samples_b_cell_line,samples_a_single_cell,samples_b_single_cell
0,GSE110685,53,Low density granulocytes and their gene signat...,GEO,https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi...,0,11,0,0,0,0
1,GSE139358,41,"Transcriptomic, epigenetic and functional anal...",GEO,https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi...,0,15,0,0,0,0
2,GSE86884,96,Differentially Expressed Gene Transcripts Usin...,GEO,https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi...,0,2,0,0,0,0

In [135]:
def get_study_info(hgnc_id,ensemble_id,lowrange,highrange,entity,term):
    url = "https://preview.nferx.com/dv/201912/rnaapi2/term_distribution?"
    params = {
        "entity_type":entity,
        "range_a_min":lowrange[0],
        "range_a_max":lowrange[1],
        "range_b_min":highrange[0],
        "range_b_max":highrange[1],
        "enriched_group": "B",
        "exclude_zero": True,
        "token_extraction": "ngram",
        "single_cell_filter":"not_single_cell",
        "cell_line_filter":"not_cell_line",
        "exclude_zero":True,
        "gene_id":ensemble_id,
        "hgnc_id":hgnc_id,
        "term":term
    }
    x = requests.get(url, params=params, headers = headers)
    required_table = json_normalize(x.json()['result']['term_features']['studies_found'])
    return(required_table)
all_IL1A_disease_enriched_high = get_study_info("il1a","ensg00000115008",[0,0.06],[3.68,14],"root-diseases","lupus")
all_IL1A_disease_enriched_high

,study_id,total_sample_count,study_title,study_type,study_link,samples_a,samples_b,samples_a_cell_line,samples_b_cell_line,samples_a_single_cell,samples_b_single_cell
0,GSE124939,164,Hypersensitive interferon responses in lupus k...,GEO,https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi...,0,80,0,0,0,0

In [136]:
all_IL1A_disease_enriched_low = get_study_info("il1a","ensg00000115008",[0,0],[0,0.06],"root-diseases","lupus")
all_IL1A_disease_enriched_low

,study_id,total_sample_count,study_title,study_type,study_link,samples_a,samples_b,samples_a_cell_line,samples_b_cell_line,samples_a_single_cell,samples_b_single_cell
0,GSE86884,96,Differentially Expressed Gene Transcripts Usin...,GEO,https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi...,0,2,0,0,0,0
1,GSE110685,53,Low density granulocytes and their gene signat...,GEO,https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi...,0,11,0,0,0,0
2,GSE139358,41,"Transcriptomic, epigenetic and functional anal...",GEO,https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi...,0,15,0,0,0,0

In [137]:
all_IL1A_disease_enriched_medium = get_study_info("il1a","ensg00000115008",[0,0.059],[0.06,3.68],"root-diseases","lupus")
all_IL1A_disease_enriched_medium

,study_id,total_sample_count,study_title,study_type,study_link,samples_a,samples_b,samples_a_cell_line,samples_b_cell_line,samples_a_single_cell,samples_b_single_cell
0,GSE124939,164,Hypersensitive interferon responses in lupus k...,GEO,https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi...,0,1,0,0,0,0
1,GSE139358,41,"Transcriptomic, epigenetic and functional anal...",GEO,https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi...,15,5,0,0,0,0

In [138]:
all_IL1A_disease_enriched_total = get_study_info("il1a","ensg00000115008",[0,0.0001],[0.001,14],"root-diseases","lupus")
all_IL1A_disease_enriched_total

,study_id,total_sample_count,study_title,study_type,study_link,samples_a,samples_b,samples_a_cell_line,samples_b_cell_line,samples_a_single_cell,samples_b_single_cell
0,GSE124939,164,Hypersensitive interferon responses in lupus k...,GEO,https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi...,0,81,0,0,0,0
1,GSE139358,41,"Transcriptomic, epigenetic and functional anal...",GEO,https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi...,0,20,0,0,0,0
2,GSE86884,96,Differentially Expressed Gene Transcripts Usin...,GEO,https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi...,0,2,0,0,0,0
3,GSE110685,53,Low density granulocytes and their gene signat...,GEO,https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi...,0,11,0,0,0,0

In [140]:
all_IL1A_disease_enriched_total.co

4

In [234]:
def get_disease_numbers(diseasename):
    all_IL1A_disease_enriched_all = get_study_info("il1a","ensg00000115008",[0,0.0001],[0.001,14],"root-diseases",diseasename)
    
    all_IL1A_disease_enriched_high = get_study_info("il1a","ensg00000115008",[0,0.06],[3.68,14],"root-diseases",diseasename)
    
    all_IL1A_disease_enriched_med = get_study_info("il1a","ensg00000115008",[0,0.059],[0.06,3.68],"root-diseases",diseasename)
    
    try:
        all_IL1A_disease_enriched_low = get_study_info("il1a","ensg00000115008",[0,0],[0,0.0599],"root-diseases",diseasename)
    except TypeError:
        all_IL1A_disease_enriched_low = pd.DataFrame(columns = list(all_IL1A_disease_enriched_high.columns))
    
    
    combined_result = str(all_IL1A_disease_enriched_high['samples_b'].sum()) + "," + str(all_IL1A_disease_enriched_high.shape[0]) + "," + str(all_IL1A_disease_enriched_med['samples_b'].sum()) + "," + str(all_IL1A_disease_enriched_med.shape[0])  + "," + str(all_IL1A_disease_enriched_low['samples_b'].sum()) + "," + str(all_IL1A_disease_enriched_low.shape[0]) + "," + str(all_IL1A_disease_enriched_all['samples_b'].sum()) + "," + str(all_IL1A_disease_enriched_all.shape[0])
    
    return(combined_result)

In [282]:
def get_disease_numbers2(diseasename):
    all_IL1A_disease_enriched_all = get_study_info("il1a","ensg00000115008",[0,0.0001],[0.001,14],"root-diseases",diseasename)
    
    try:
        all_IL1A_disease_enriched_high = get_study_info("il1a","ensg00000115008",[0,0.06],[3.68,14],"root-diseases",diseasename)
    except TypeError:
        all_IL1A_disease_enriched_high = pd.DataFrame(columns=list(all_IL1A_disease_enriched_all.columns))
    
    try:
        all_IL1A_disease_enriched_med = get_study_info("il1a","ensg00000115008",[0,0.059],[0.06,3.68],"root-diseases",diseasename)
    except TypeError:
        all_IL1A_disease_enriched_med = pd.DataFrame(columns=list(all_IL1A_disease_enriched_all.columns))
    
    try:
        all_IL1A_disease_enriched_low = get_study_info("il1a","ensg00000115008",[0,0],[0,0.0599],"root-diseases",diseasename)
    except TypeError:
        all_IL1A_disease_enriched_low = pd.DataFrame(columns=list(all_IL1A_disease_enriched_all.columns))
    
    
    combined_result = str(all_IL1A_disease_enriched_high['samples_b'].sum()) + "," + str(all_IL1A_disease_enriched_high.shape[0]) + "," + str(all_IL1A_disease_enriched_med['samples_b'].sum()) + "," + str(all_IL1A_disease_enriched_med.shape[0])  + "," + str(all_IL1A_disease_enriched_low['samples_b'].sum()) + "," + str(all_IL1A_disease_enriched_low.shape[0]) + "," + str(all_IL1A_disease_enriched_all['samples_b'].sum()) + "," + str(all_IL1A_disease_enriched_all.shape[0])
    
    return(combined_result)

In [190]:
get_study_info("il1a","ensg00000115008",[0,0],[0,0.06],"root-diseases","lupus")

,study_id,total_sample_count,study_title,study_type,study_link,samples_a,samples_b,samples_a_cell_line,samples_b_cell_line,samples_a_single_cell,samples_b_single_cell
0,GSE110685,53,Low density granulocytes and their gene signat...,GEO,https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi...,0,11,0,0,0,0
1,GSE139358,41,"Transcriptomic, epigenetic and functional anal...",GEO,https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi...,0,15,0,0,0,0
2,GSE86884,96,Differentially Expressed Gene Transcripts Usin...,GEO,https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi...,0,2,0,0,0,0

In [256]:
get_study_info("il1a","ensg00000115008",[0,0.06],[3.68,14],"root-diseases","lupus").columns

Index(['study_id', 'total_sample_count', 'study_title', 'study_type',
       'study_link', 'samples_a', 'samples_b', 'samples_a_cell_line',
       'samples_b_cell_line', 'samples_a_single_cell',
       'samples_b_single_cell'],
      dtype='object')

In [210]:
get_study_info("il1a","ensg00000115008",[0,0],[0,0.059],"root-diseases","lupus")

,study_id,total_sample_count,study_title,study_type,study_link,samples_a,samples_b,samples_a_cell_line,samples_b_cell_line,samples_a_single_cell,samples_b_single_cell
0,GSE110685,53,Low density granulocytes and their gene signat...,GEO,https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi...,0,11,0,0,0,0
1,GSE139358,41,"Transcriptomic, epigenetic and functional anal...",GEO,https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi...,0,15,0,0,0,0
2,GSE86884,96,Differentially Expressed Gene Transcripts Usin...,GEO,https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi...,0,2,0,0,0,0

In [292]:
get_disease_numbers2("tuberculosis")

'1,1,21,2,4,1,26,3'

In [262]:
get_disease_numbers2("recessive_dystrophic_epidermolysis_bullosa")

'3,1,17,2,0,0,20,2'

In [255]:
get_study_info("il1a","ensg00000115008",[0,0.06],[3.86,14],"root-diseases","chorioamnionitis")

,study_id,total_sample_count,study_title,study_type,study_link,samples_a,samples_b,samples_a_cell_line,samples_b_cell_line,samples_a_single_cell,samples_b_single_cell
0,GSE111927,11,Effect of chorioamnionitis exposure on neonata...,GEO,https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi...,0,5,0,0,0,0

In [220]:
url = "https://preview.nferx.com/dv/201912/rnaapi2/term_distribution?"

#https://preview.nferx.com/rnaapi2/entity_distribution?hgnc_id=il1a&gene_id=ensg00000115008&range_a_min=0&range_a_max=0.07&range_b_min=3.86&range_b_max=14&entity_type=root-cells-and-tissues&enriched_group=B&cell_line_filter=not_cell_line&single_cell_filter=not_single_cell&exclude_zero=true&token_extraction=ngram

params = {
    "entity_type":"root-diseases",
    "range_a_min":0,
    "range_a_max":0.06,
    "range_b_min":3.86,
    "range_b_max":14,
    "enriched_group": "B",
    "exclude_zero": True,
    "token_extraction": "ngram",
    "single_cell_filter":"not_single_cell",
    "cell_line_filter":"all",
    "exclude_zero":True,
    "gene_id":"ensg00000115008",
    "hgnc_id":"IL1A",
    "term" : "acute_on_chronic_liver_failure"
}

x = requests.get(url, params=params, headers = headers)
all_data = json_normalize(x.json()['result']['term_features'])
all_data

,cell_line_data_a,cell_line_data_b,range_a_ratio,range_b_ratio,range_a_count,range_b_count,range_a_count_cell_line,range_b_count_cell_line,range_a_count_single_cell,range_b_count_single_cell,term,confounding_terms,studies_found
0,None,None,0,0.01,0,40,0,0,0,0,acute_on_chronic_liver_failure,"[{'term': 'liver', 'samples_count': 40, 'all_c...","[{'study_id': 'GSE93265', 'total_sample_count'..."

In [225]:
len(all_data['studies_found'].values)

1